cmake/configs/default.cmake, cmake/projects/jsonrpc-lean/hunter.cmake
=> Add jsonrpc-lean

cmake/configs/default.cmake, cmake/projects/absl/hunter.cmake
abseil v. lts-2020-02-25
Signed-off-by: Igor Egorov <igor@soramitsu.co.jp>
=> Hunterize abseil

cmake/projects/sr25519/hunter.cmake
* Change the name from sr25519 to schnorrkel
* Update the URL and SHA1
* https://github.com/soramitsu/kagome/pull/577/checks?check_run_id=1331069212
* https://travis-ci.org/github/soramitsu/kagome/builds/740137978
=> Update config for schnorrkel_crust

cmake/configs/default.cmake, cmake/projects/sr25519/hunter.cmake
Set schnorrkel-crust default version to 0.2.0
---
=> Update schnorrkel version

cmake/configs/default.cmake
=> Remove duplication of schnorrkel default version in default.cmake

cmake/configs/default.cmake, cmake/projects/soralog/hunter.cmake
I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/create/cmake.html)
=> Add Soralog v0.0.1

cmake/configs/default.cmake, cmake/projects/soralog/hunter.cmake
Signed-off-by: Dmitriy Khaustov aka xDimon <khaustov.dm@gmail.com>
=> Update Soralog to v0.0.2

cmake/configs/default.cmake, cmake/projects/soralog/hunter.cmake
I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/create/cmake.html) step by step carefully. **Yes**
=> Update Soralog to v0.0.3

cmake/configs/default.cmake, cmake/projects/soralog/hunter.cmake
=> Update Soralog to v0.0.7

cmake/configs/default.cmake, cmake/projects/soralog/hunter.cmake
Signed-off-by: Dmitriy Khaustov aka xDimon <khaustov.dm@gmail.com>
---
=> Update Soralog to v0.0.8

cmake/projects/Boost.DI/hunter.cmake
* I've not tested this package remotely and haven't excluded any broken builds.
Here are no links to the Travis/AppVeyor with status "All passed".
=> Update boost.di link to soramitsu's fork

cmake/projects/wavm/hunter.cmake
=> update wavm 1.0.5

cmake/projects/soralog/hunter.cmake
=> update soralog 0.1.4

cmake/projects/erasure_coding_crust/hunter.cmake
=> Add v0.0.5 of erasure_coding_crust

cmake/configs/default.cmake, cmake/projects/Boost/hunter.cmake
---
* This update will break a few toolchains.
- Toolchain 1
- Toolchain 2
* This update will fix a few toolchains.
- Toolchain 1
- Toolchain 2
---
* I've checked this [Git style guide](https://0.readthedocs.io/en/latest/git.html). **[Yes|No]**
* I've checked this [CMake style guide](https://0.readthedocs.io/en/latest/cmake.html). **[Yes|No]**
* My change will work with CMake 3.2 (minimum requirement for Hunter). **[Yes|No]**
* …
=> Feature/boost 1.83

cmake/projects/Boost.DI/hunter.cmake, cmake/projects/Clang/hunter.cmake, cmake/projects/LLVM/hunter.cmake, cmake/projects/binaryen/hunter.cmake, cmake/projects/erasure_coding_crust/hunter.cmake, cmake/projects/soralog/hunter.cmake, cmake/projects/wavm/hunter.cmake
* I've checked this [Git style guide](https://0.readthedocs.io/en/latest/git.html). **[Yes]**
* I've checked this [CMake style guide](https://0.readthedocs.io/en/latest/cmake.html). **[Yes]**
* My change will work with CMake 3.2 (minimum requirement for Hunter). **[Yes]**
* I will try to keep this pull request as small as possible and will try not to mix unrelated features. **[Yes]**
---
=> Feature/dops 2716/update hunter links

cmake/projects/Boost.DI/hunter.cmake
* I've checked this [Git style guide](https://0.readthedocs.io/en/latest/git.html). **[Yes]**
* I've checked this [CMake style guide](https://0.readthedocs.io/en/latest/cmake.html). **[Yes]**
* My change will work with CMake 3.2 (minimum requirement for Hunter). **[Yes]**
* I will try to keep this pull request as small as possible and will try not to mix unrelated features. **[Yes]**
---
=> Fix SHA1 for Boost.DI

cmake/projects/soralog/hunter.cmake
---
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update …
=> Fix soralog archive

cmake/configs/default.cmake, cmake/projects/LLVM/hunter.cmake, cmake/projects/wavm/hunter.cmake
---
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update …
=> Update LLVM and WAVM

cmake/projects/WasmEdge/hunter.cmake
step by step carefully. **No**
---
=> WasmEdge v0.13.3-qdrvm1

cmake/projects/libsecp256k1/hunter.cmake
=> libsecp256k1 build

cmake/configs/default.cmake, cmake/projects/LLD/hunter.cmake, cmake/projects/LLVM/hunter.cmake
---
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update …
=> Update llvm, lld

cmake/configs/default.cmake, cmake/projects/soralog/hunter.cmake
=> Update soralog to version 0.2.2

cmake/configs/default.cmake, cmake/projects/Boost.DI/hunter.cmake
=> update boost di

cmake/configs/default.cmake, cmake/projects/Boost/hunter.cmake
Fixes broken Boost download links.
Adds versions 1.85.0-gh and 1.86.0-gh.
Boost 1.87 was tested also and not included by now due to build issues.
1.85 & 1.86 both were tested with libp2p. 1.85 was also tested with kagome.
see this merged pull request …
=> Add Boost versions 1.85 & 1.86 pointed to GitHub

cmake/configs/default.cmake, cmake/projects/Boost/hunter.cmake
---
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update …
=> Update Boost sources and add 1.87.0
